# config.yml
datasets:
  - name: "FA-KES"
    description: "FA-KES news dataset of misinformation during the Syrian War"
    path: "/data/transformed/FA-KES.csv"
    input_keys:
      - unit_id
      - article_title
      - article_content
      - source
      - date
      - location
    output_keys:
      - label
  - name: "FA-KES test"
    description: "FA-KES news dataset of misinformation during the Syrian War"
    path: "/data/transformed/FA-KES.csv"
    input_keys:
      - unit_id
      - article_title
      - article_content
      - source
      - date
      - location
    output_keys:
      - label
    row_count: 100
  - name: "FA-KES debug"
    description: "Dataset for debugging"
    path: "/data/transformed/FA-KES.csv"
    input_keys:
      - unit_id
      - article_title
      - article_content
      - source
      - date
      - location
    output_keys:
      - label
    row_count: 5
  - name: "ReCOVery News"
    description: "ReCOVery news dataset of misinformation during the COVID-19 pandemic"
    path: "/data/transformed/recovery-news-data.csv"
    input_keys:
      - news_id
      - article_title
      - article_content
      - publisher
      - publish_date
    output_keys:
      - label
  - name: "ReCOVery News test"
    description: "ReCOVery news dataset of misinformation during the COVID-19 pandemic"
    path: "/data/transformed/recovery-news-data.csv"
    input_keys:
      - news_id
      - article_title
      - article_content
      - publisher
      - publish_date
    output_keys:
      - label
    row_count: 100
  - name: "politifact"
    description: "Politifact news dataset of misinformation"
    path: "/data/transformed/politifact.csv"
    input_keys:
      - article_title
      - article_content
      - statement_originator
      - statement_source
      - statement_date
    output_keys:
      - label