# config.yml
datasets:
  - name: "FA-KES_None"
    description: "FA-KES"
    path: "/data/raw/FA-KES.csv"
    transform: "FA-KES"       
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    chunk_size: 50
    

  - name: "FA-KES_100"
    description: "FA-KES (100 balanced rows)"
    path: "/data/raw/FA-KES.csv"
    transform: "FA-KES"      
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    total_samples: 100

  - name: "FA-KES_10" 
    description: "FA-KES (10 balanced rows)"
    path: "/data/raw/FA-KES.csv"
    transform: "FA-KES"
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    total_samples: 10

  - name: "recovery-news-data_None"
    description: "ReCOVery news dataset of misinformation during the COVID-19 pandemic"
    path: "/data/raw/recovery-news-data.csv"
    transform: "recovery-news-data"
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    chunk_size: 50
    

  - name: "recovery-news-data_100" 
    description: "ReCOVery news dataset of misinformation during the COVID-19 pandemic"
    path: "/data/raw/recovery-news-data.csv"
    transform: "recovery-news-data"
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    total_samples: 100

  - name: "politifact"
    description: "Politifact news dataset of misinformation"
    path: "/data/raw/politifact_factcheck_data.json"
    transform: "politifact"
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    chunk_size: 50
    

  - name: "politifact_100"
    description: "Politifact news dataset of misinformation"  
    path: "/data/raw/politifact_factcheck_data.json"
    transform: "politifact"
    input_keys: ["article_title", "article_content"]
    output_keys: ["label"]
    total_samples: 100
