---
models:
  bias:
    description: Bias classification model using distil roberta
    max_length: 512
    name: valurank/distilroberta-bias
    type: text-classification
  call_to_action:
    description: Call to action detection model using distilroberta
    max_length: 512
    name: chaichy/gbert-CTA-w-synth
    type: text-classification
  clickbait:
    description: Tile clickbait detection model using XLM_RoBERTa
    max_length: 512
    name: christinacdl/XLM_RoBERTa-Large-Clickbait-Detection-NEW-Data
    type: text-classification
  emotional_valence:
    description: 'Emotion detection model using distilroberta which classifies text into 7 classes: ''joy'', ''neutral'', ''fear'', ''surprise'', ''sadness'', ''anger'', ''disgust'''
    max_length: 512
    name: j-hartmann/emotion-english-distilroberta-base
    type: text-classification
  impoliteness:
    description: 'Politeness classification - categorizes text as polite, neutral, impolite, etc. Polite Guard specifically has four classes: polite, somewhat polite, neutral, impolite'
    max_length: 512
    name: Intel/polite-guard
    type: text-classification
  incivility:
    description: Toxicity detection - classifies text as toxic/uncivil vs. not (it detects insults, harassment, profanity, etc.,
    max_length: 512
    name: martin-ha/toxic-comment-model
    type: text-classification
  # incorrect_spelling:
    #   name: "oliverguhr/spelling-correction-english-base"
    #   type: "text-classification"
    #   description: "Spelling error detection model using SpellBERT"
    #   max_length: 1024
  informal_tone:
    description: Formality detection model using RoBERTa
    max_length: 512
    name: s-nlp/roberta-base-formality-ranker
    type: text-classification
  personal_perspective:
    description: Fine-tuned mDeBERTa V3 model for subjectivity detection
    label_mapping:
      LABEL_0: objective
      LABEL_1: subjective
    max_length: 512
    name: GroNLP/mdebertav3-subjectivity-english
    type: text-classification
  polarising_language:
    description: Polarization detection model using XLM-RoBERTa
    max_length: 512
    name: Sami92/XLM-R-Large-Polarization-Classifier
    type: text-classification
  sensationalism:
    description: Sensationalism detection - classifies whether a statement is sensationalistic or not (e.g., uses exaggerated or shocking language)
    max_length: 512
    name: Sami92/XLM-R-Large-Sensationalism-Classifier
    type: text-classification
  topic:
    description: News topic classification model based on xlm-roberta-large 
    name: classla/multilingual-IPTC-news-topic-classifier
    type: text-classification
    max_length: 512